services:
  - type: web
    name: devera-backend
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        generateValue: true
      - key: MONGODB_URL
        sync: false
      - key: CORS_ORIGIN
        sync: false
      - key: ACCESS_TOKEN_SECRET
        generateValue: true
      - key: ACESS_TOKEN_EXPIN
        value: 15d
      - key: REFRESH_TOKEN_SECRET
        generateValue: true
      - key: REFRESH_TOKEN_EXPIN
        value: 30d

